name: jedha_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - boto3
  - python-dotenv
  - scikit-learn
  - fsspec
  - s3fs
  - plotly
  - matplotlib
  - seaborn
  - statsmodels
